# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfil
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres

development:
  <<: *default
  database: "devise"

test:
  <<: *default
  database: "test"

#production:
#  <<: *default
#∫  database: db/production.sqlite3
